import {chromium} from '/Users/larry/.workbuddy/binaries/node/workspace/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const browser=await chromium.launch({executablePath:'/Users/larry/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell'});
const ctx=await browser.newContext({viewport:{width:390,height:844}});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const checks=[];const add=(name,pass,detail)=>checks.push({name,pass,detail});
await p.goto('http://127.0.0.1:41839/atlas.html#4-03');await p.waitForTimeout(2200);
add('页面身份/内容/无遮罩',await p.title()==='大语言模型 · 银河AI知识图册'&&await p.locator('#definition').innerText()!==''&&await p.locator('vite-error-overlay').count()===0,p.url());
add('实际197节点1562边与直接线分类',await p.evaluate(()=>{const g=atlasUI.graph(),id=atlasUI.getState().selected;return g.graphData().nodes.length===197&&g.graphData().links.length===1562&&g.graphData().links.every(e=>{const a=e.effective_source===id||e.effective_target===id;return e.__lineObj.material.linewidth===(a?1.6:.6)&&e.__lineObj.material.opacity===(a?.94:.48)})}));
const render=await p.evaluate(()=>{let bad=[];for(const id of atlasUI.getState().visible){atlasUI.selectConcept(id);const c=atlasUI.readCard(id);const def=document.querySelector('#definition').textContent;const plain=[...document.querySelectorAll('#explanation-copy .plain-explanation p')].map(x=>x.textContent).join('\n');const fields=[...document.querySelectorAll('#explanation-copy [data-field]')].map(x=>({k:x.dataset.field,v:x.querySelector('span:last-child').textContent}));if(def!==c.fields['精确定义']||plain!==c.fields['通俗解释'].split('\n').filter(Boolean).join('\n')||fields.some(x=>x.v!==c.fields[x.k]))bad.push(id)}return bad});add('197卡实际DOM定义/新增说明/既有字段映射',!render.length,render);
await p.goto('http://127.0.0.1:41839/atlas.html#4-03');await p.reload();await p.waitForTimeout(2200);
await p.evaluate(()=>{document.querySelector('.neighbor-card summary').click();document.querySelector('[data-group="related"]').open=true});await p.waitForTimeout(350);
const old=await p.evaluate(()=>({neighbor:document.querySelector('.neighbor-card[open]').dataset.neighbor,related:document.querySelector('[data-group="related"]').open}));
await p.evaluate(()=>atlasUI.selectConcept('3-07'));await p.waitForTimeout(700);await p.goBack();await p.waitForTimeout(600);
const restored=await p.evaluate(()=>({sel:atlasUI.getState().selected,neighbor:document.querySelector('.neighbor-card[open]')?.dataset.neighbor??null,related:document.querySelector('[data-group="related"]').open}));add('后退恢复相邻词条及分组展开',restored.neighbor===old.neighbor&&restored.related===old.related,{old,restored});
await p.evaluate(()=>atlasUI.selectConcept('3-04'));await p.waitForTimeout(700);
await p.evaluate(()=>{document.querySelector('#explanation').open=true;scrollTo(0,160)});await p.waitForTimeout(450);
await p.evaluate(()=>document.querySelector('#explanation').open=false);await p.goBack();await p.waitForTimeout(450);await p.goForward();await p.waitForTimeout(450);
const fast=await p.evaluate(()=>({id:atlasUI.getState().selected,open:document.querySelector('#explanation').open}));add('收起说明后立即后退再前进保持收起',fast.id==='3-04'&&!fast.open,fast);
await p.evaluate(()=>atlasUI.selectConcept('3-07'));await p.waitForTimeout(700);await p.evaluate(()=>{document.querySelector('#explanation').open=false;scrollTo(0,160)});await p.waitForTimeout(450);const prev=await p.evaluate(()=>({cam:atlasUI.getState().camera,scroll:scrollY}));await p.goBack();await p.waitForTimeout(450);await p.goForward();await p.waitForTimeout(450);const next=await p.evaluate(()=>({id:atlasUI.getState().selected,open:document.querySelector('#explanation').open,cam:atlasUI.getState().camera,scroll:scrollY}));add('等待同步后的主状态前进后退',next.id==='3-07'&&!next.open&&Math.abs(next.scroll-prev.scroll)<2,{prev,next});
await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:'/tmp/atlas55-current.png'});
for(const w of [320,430]){await p.setViewportSize({width:w,height:844});add(w+'px无溢出',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}
await p.setViewportSize({width:390,height:844});await p.click('[data-action="search"]');await p.fill('#search-input','不存在的概念xyz');add('搜索零结果提示',await p.locator('#results').innerText().then(x=>x.includes('没有匹配')));await p.keyboard.press('Escape');
const lost=await p.evaluate(()=>{const g=atlasUI.graph(),ext=g.renderer().getContext().getExtension('WEBGL_lose_context');if(!ext)return false;ext.loseContext();return true});await p.waitForTimeout(400);add('真实WebGL上下文丢失后阅读可用',lost&&await p.locator('#graph-error').isVisible()&&await p.locator('#definition').innerText()!=='');
add('正常流程无页面异常',!errors.length,errors);
const q=await ctx.newPage();try{await q.goto('http://127.0.0.1:41840/atlas.html');await q.waitForTimeout(2200);add('独立构建实际加载/字体/新增内容',await q.evaluate(async()=>{await document.fonts.ready;return atlasUI.graph().graphData().nodes.length===197&&document.querySelector('.plain-explanation').textContent.length>0&&document.fonts.check('16px AtlasSerif')}));}catch(e){add('独立构建服务可达',false,e.message)}
await browser.close();fs.writeFileSync('/tmp/atlas55-browser.json',JSON.stringify({checks},null,2));console.log(JSON.stringify(checks,null,2));
