async(page)=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const check=(name,pass,detail)=>{checks.push({name,pass:!!pass,detail});if(!pass)throw Error(name+JSON.stringify(detail));};
 const read=()=>page.evaluate(()=>{const g=atlasUI.graph(),s=atlasUI.getState(),r=document.querySelector('#graph-surface').getBoundingClientRect();return {selected:s.selected,boxes:s.labelBoxes,r:r.toJSON(),camera:g.camera().position.toArray(),target:g.controls().target.toArray(),distance:g.camera().position.distanceTo(g.controls().target),nodes:g.graphData().nodes.map(n=>({id:n.id,p:[n.x,n.y,n.z],sprite:n.__threeObj.children.find(o=>o.isSprite)?{color:n.__threeObj.children.find(o=>o.isSprite).color,bg:n.__threeObj.children.find(o=>o.isSprite).backgroundColor}:null})),edges:g.graphData().links.map(e=>({a:e.source.id,b:e.target.id,kind:e.relation_type,type:e.__lineObj.type,width:e.__lineObj.material.linewidth,opacity:e.__lineObj.material.opacity,world:e.__lineObj.material.worldUnits,positions:Array.from(e.__lineObj.geometry.attributes.instanceStart.data.array)}))}});
 const dist=(a,b)=>Math.hypot(...a.map((v,i)=>v-b[i]));
 await page.setViewportSize({width:390,height:844});await page.reload();await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(2200);const before=await read();
 check('当前概念文字与底色高亮，其余恢复原色',before.nodes.every(n=>n.sprite.color===(n.id===before.selected?'#8b4c19':'#253d35')&&n.sprite.bg===(n.id===before.selected?'#fff0d0':'rgba(248,246,241,0.94)')),null);
 check('直接连线1.6px/94%，其余0.85px/72%',before.edges.every(e=>{const active=e.a===before.selected||e.b===before.selected;return e.type==='Line2'&&!e.world&&e.width===(active?1.6:.85)&&e.opacity===(active?.94:.72)}),null);
 check('完整197/1562及78条前置关系保持',before.nodes.length===197&&before.edges.length===1562&&before.edges.filter(e=>e.kind==='prerequisite').length===78,null);
 check('每条线的几何端点绑定真实节点',before.edges.every(e=>{const a=before.nodes.find(n=>n.id===e.a).p,b=before.nodes.find(n=>n.id===e.b).p;return dist(e.positions.slice(0,3),a)<.001&&dist(e.positions.slice(3),b)<.001}),null);
 await page.screenshot({path:'output/playwright/atlas51/current-390.png'});
 const box=before.boxes.find(b=>b.id===before.selected);await page.mouse.move(before.r.x+(box.left+box.right)/2,before.r.y+(box.top+box.bottom)/2);await page.mouse.down();await page.mouse.move(before.r.x+(box.left+box.right)/2+35,before.r.y+(box.top+box.bottom)/2+20,{steps:8});await page.waitForTimeout(160);const dragged=await read();await page.mouse.up();await page.waitForTimeout(1500);
 check('真实拖动仍变形，更新加粗线端点，镜头不移动',dragged.selected===before.selected&&dist(dragged.camera,before.camera)<.01&&dist(dragged.nodes.find(n=>n.id===before.selected).p,before.nodes.find(n=>n.id===before.selected).p)>10&&dragged.edges.some((e,i)=>dist(e.positions,before.edges[i].positions)>1),null);
 await page.locator('[data-action="overview"]').click();await page.waitForTimeout(80);const overview=await read(),other=overview.boxes.find(b=>b.id!==overview.selected);
 await page.mouse.click(overview.r.x+(other.left+other.right)/2,overview.r.y+(other.top+other.bottom)/2);await page.waitForTimeout(530);const clicked=await read();
 check('切换概念后高亮及线宽同步迁移，坐标保持',clicked.selected===other.id&&clicked.nodes.every(n=>dist(n.p,overview.nodes.find(m=>m.id===n.id).p)<.01)&&clicked.nodes.every(n=>n.sprite.color===(n.id===clicked.selected?'#8b4c19':'#253d35'))&&clicked.edges.every(e=>e.width===(e.a===clicked.selected||e.b===clicked.selected?1.6:.85)),{selected:clicked.selected});
 await page.mouse.move(clicked.r.x+clicked.r.width*.65,clicked.r.y+clicked.r.height*.55);await page.mouse.wheel(0,-240);await page.waitForTimeout(180);const zoomed=await read();check('缩放时像素线宽保持，选择不变',zoomed.distance<clicked.distance&&zoomed.selected===clicked.selected&&zoomed.edges.every((e,i)=>e.width===clicked.edges[i].width),null);
 await page.screenshot({path:'output/playwright/atlas51/switched-390.png'});
 for(const width of [320,430]){await page.setViewportSize({width,height:844});await page.evaluate(()=>scrollTo(0,0));check(width+'px无横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),null);await page.screenshot({path:'output/playwright/atlas51/current-'+width+'.png'});}
 check('无应用异常或错误遮罩',errors.length===0&&await page.locator('vite-error-overlay').count()===0,errors);
 return {checks,errors,environment:{url:page.url(),viewports:[320,390,430]},before,clicked};
}
